Bluetooth node
vortexntnu/rov-control pull request #18
Opened 2017-05-03 10:59 UTC by vegkams

Node for reading strings broadcast over bluetooth and publishing the received string as a ROS topic.

2017-05-03 12:00 UTC, sindrehan requested changes
Remove the unnecessary length variable and I am pleased.

2017-05-03 12:00 UTC, sindrehan commented on bluetooth/scripts/hc-05_interface.py
> +        leneol = len(eol)
`leneol` is unnecessary.

2017-05-03 12:42 UTC, mortenfyhn requested changes
Looks good, but look at the comments before merging

2017-05-03 12:42 UTC, mortenfyhn commented on bluetooth/launch/bluetooth.launch
> +</launch>
Add newline at end of file

2017-05-03 12:42 UTC, mortenfyhn commented on bluetooth/scripts/hc-05_interface.py
> +            rospy.Rate(10).sleep()
Maybe make spin rate a "constant" outside the class?

2017-05-03 12:42 UTC, mortenfyhn commented on vortex_msgs/msg/ContainerID.msg
> +string container_id
Newline

2017-05-04 07:17 UTC, sindrehan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bluetooth-node](https://trello.com/c/ub8XMAn7/175-bluetooth-node)

2017-05-04 08:59 UTC, mortenfyhn approved these changes
Looks good to me

2017-05-04 09:00 UTC, sindrehan approved these changes
Very good.

2017-05-04 09:02 UTC, merged