Light node
vortexntnu/rov-control pull request #21
Opened 2017-05-05 18:44 UTC by vegkams

Test before merge

2017-05-05 18:50 UTC, vegkams commented
![](https://github.trello.services/images/mini-trello-icon.png) [Lys-node](https://trello.com/c/DK7ongbA/191-lys-node)

2017-05-06 15:15 UTC, mortenfyhn requested changes
Looks good, overall. Let's test it on hw before merging.

2017-05-06 15:15 UTC, mortenfyhn commented on vortex_msgs/msg/LightInput.msg
> +uint8[] intensity
Update documentation here. Mention that the indices of the lists correspond (if they do). Specify the range for intensity values. Is it 0-255?

2017-05-06 15:47 UTC, mortenfyhn approved these changes

2017-05-06 17:58 UTC, sindrehan commented on light/README.md
> +Node for controlling the ROV lights
A more extensive Readme would be nice.

2017-05-06 17:58 UTC, sindrehan commented on light/README.md
> +Node for controlling the ROV lights
E.g. add a line or two about the dependencies.

2017-05-06 17:58 UTC, sindrehan commented on light/scripts/light_node.py
> +FULL_CYCLE = 4096
Should be 4095.

2017-05-06 17:58 UTC, sindrehan commented on light/scripts/light_node.py
> +FULL_CYCLE = 4096
Consider loading parameter from manipulator branch.

2017-05-06 17:58 UTC, sindrehan commented on light/scripts/light_node.py
> +                Pwm.off = (FULL_CYCLE * msg.intensity[index]) // 100
- Pwm.off is a list and need an index.

2017-05-06 19:18 UTC, sindrehan approved these changes

2017-05-06 22:27 UTC, merged