Manipulator node
vortexntnu/rov-control pull request #26
Opened 2017-05-06 21:59 UTC by mortenfyhn

2017-05-06 22:43 UTC, fonstein requested changes

2017-05-06 22:43 UTC, fonstein commented on manipulator_interface/scripts/manipulator_interface.py
> +        rospy.sleep(0.1) # Initial set to zero seems to disappear without a short sleep here
wat

2017-05-06 22:43 UTC, fonstein commented on vortex_msgs/msg/Manipulator.msg
> +bool close_valve
This is wrong. Fix plz.

2017-05-06 23:06 UTC, mortenfyhn commented on manipulator_interface/scripts/manipulator_interface.py
> +        rospy.sleep(0.1) # Initial set to zero seems to disappear without a short sleep here
¯\_(ツ)_/¯

2017-05-06 23:10 UTC, sindrehan commented on manipulator_interface/scripts/manipulator_interface.py
> +        rospy.sleep(0.1) # Initial set to zero seems to disappear without a short sleep here
You dropped this:  \

2017-05-06 23:10 UTC, sindrehan commented on vortex_msgs/msg/Manipulator.msg
> +bool close_valve
I will fix this.

2017-05-06 23:35 UTC, sindrehan commented on manipulator_interface/scripts/stepper.py
> +                GPIO.output(pin[i], GPIO.HIGH)
Should `pin` be `self.pins`? Can't find the declaration of `pin`. Same goes for line 80.

2017-05-07 08:11 UTC, mortenfyhn commented on manipulator_interface/scripts/stepper.py
> +                GPIO.output(pin[i], GPIO.HIGH)
Yes. I fix.

2017-05-08 15:23 UTC, fonstein approved these changes

2017-05-08 15:24 UTC, merged