Change pwm msg
vortexntnu/rov-control pull request #31
Opened 2017-06-08 17:14 UTC by vegkams

Move conversion from microseconds to bits to the PWM node.

2017-06-08 17:27 UTC, sindrehan requested changes

2017-06-08 17:27 UTC, sindrehan commented on vortex_msgs/msg/Pwm.msg
> +uint16[] microseconds
Rename to positive_width_us

2017-06-09 09:06 UTC, sindrehan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Change pwm message to μs](https://trello.com/c/MinfIb4C/212-change-pwm-message-to-%CE%BCs)

2017-06-09 09:11 UTC, sindrehan approved these changes
Seems good. Needs testing before merging.

2017-06-09 09:11 UTC, sindrehan commented on vortex_msgs/msg/Pwm.msg
> +# PWM pin nrs
> nrs

Really?

2017-06-09 09:42 UTC, vegkams commented on vortex_msgs/msg/Pwm.msg
> +# PWM pin nrs
Did you mean rly?

2017-06-10 11:53 UTC, merged