Bug/allocator always pub
vortexntnu/rov-control pull request #53
Opened 2018-02-11 17:08 UTC by mortenfyhn

Fixes #48 and cleans up the allocator a bit. A lot of renames, using a unique pointer so we don't have to worry about `delete`, and some more stuff.

2018-02-11 17:14 UTC, mortenfyhn commented
Never mind the tests...

2018-02-11 17:24 UTC, sindrehan requested changes
Roslint is whining, see comments.

2018-02-11 17:24 UTC, sindrehan commented on vortex_allocator/include/vortex_allocator/allocator_ros.h
> +  Allocator(ros::NodeHandle nh);
Roslint:
`vortex_allocator/include/vortex_allocator/allocator_ros.h:15:  Single-parameter constructors should be marked explicit.  [runtime/explicit] [5]`

2018-02-11 17:24 UTC, sindrehan commented on vortex_allocator/src/allocator_ros.cpp
> + :
Roslint: 
`vortex_allocator/src/allocator_ros.cpp:13:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]`

2018-02-11 17:25 UTC, sindrehan commented
@mortenfyhn Why ignore the tests?

2018-02-20 14:39 UTC, sindrehan approved these changes

2018-02-24 11:11 UTC, merged